### ISSUE TITLE
double selection d'une activité

### ISSUE THREAD

**Issue by taccary** [taccary/suivi-sio#1]
Situation onglet activité
Lorsqu'on re-selectionne une activité déjà sélectionnée et qu'on enregistre pas, toutes les activités et reformulations sont effacées (déréférencées ? à vérifier)

**Comment by ghost** [comment]
Solution : dans loadcomp.js, ajouter le else
if (nouveau){
		frmchoi.options[nb] = new Option(frmprop.options[num].text, value, false, false);
		choix.push(value);//ajoute dans choix
		majchoix();
		frmchoi = frm.compchoisies;
		nb = frmchoi.length;
		nbcomp = tab[value].length;
		for (i=0 ; i<nbcomp ; i++)
			frmchoi.options[nb++] = new Option(tab[value][i], value, false, false);
		frmchoi.options[nb] = new Option('------------', value, false, false);
	}
	else majchoix();

**Comment by taccary** [comment]
solution mise en prod
