### ISSUE TITLE
Bug lors du changement du mot de passe

### ISSUE THREAD

**Issue by icof69** [taccary/suivi-sio#5]
![image](https://user-images.githubusercontent.com/39825890/40832088-f1eb4cec-658a-11e8-9929-9fa2c2a27ba2.png)

**Comment by ghost** [comment]
Tous ce passe dans model.class.php, dans les lignes 508,509,510. Il y a une requête SQL, qui pose problème. Quand on la lance dans Uwamp elle Marche bien.
Résolution du problème: Il faut enlever les lignes 508,509,510 de modèle.class.php qui est dans le dossier class, 
//$req='select numGroupe from '.$this->pref.'etudiant where num='.$num;
//$res=$this->mysql->execSQL($req);
//$gr=$res[0]["numGroupe"];
Les professeurs n'ont pas besoins d'une requête pour changer leur mot de passe, il peuvent changer leur mot de passe.

**Comment by taccary** [comment]
mise en prod ok, je passe le ticket en résolu
